name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
permissions:
  contents: write

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: "Spellcheck"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade codespell
      - name: Run spellcheck
        run: |
          codespell $(git ls-files '*.tex')

  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            texlive-base biber latexmk asymptote
            texlive-latex-recommended texlive-latex-extra texlive-science
      - name: texconfig rehash
        run: sudo texconfig rehash
      - name: Compile document
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error Napkin.tex
      - name: Create dist folder
        run: |
          mkdir -p dist
          mkdir -p dist/asy
          cp Napkin.log dist/
          cp Napkin.pdf dist/
          cp asy/*.asy dist/
          cd dist
          tree -H '.' -I "index.html" -D --charset utf-8 -T "An Infinitely Large Napkin" >index.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: napkin-dist
          path: dist/
      - name: Deploy dist folder to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
